# Brings up the development server via a docker compose script
version: '3.4'

services:
    tsp:
        build: 
            context: .
            target: dev
        container_name: cis422_tsp
        tty: true
        ports:
            - 5000:5000
        environment:
            - CONFIG_LOC=/run/secrets/config
        volumes:
            - .:/app
            - ./config.json:/run/secrets/config
